### ISSUE TITLE
Bank import: unable to create payment entry

### ISSUE THREAD

**Issue by lasalesi** [lasalesi/myapp#1]
When trying to insert payment entries, the following error occurs:

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/myapp/myapp/myapp/page/bankimport/bankimport.py", line 81, in parse_file
    new_records = parse_ubs(content, account)
  File "/home/frappe/frappe-bench/apps/myapp/myapp/myapp/page/bankimport/bankimport.py", line 65, in parse_ubs
    inserted_payment_entry = new_payment_entry.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 47, in validate
    self.set_amounts()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 256, in set_amounts
    self.set_unallocated_amount()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 292, in set_unallocated_amount
    self.unallocated_amount = party_amount - (self.total_allocated_amount - total_deductions)
TypeError: unsupported operand type(s) for -: 'unicode' and 'int'
```

**Steps to reproduce:**
* select a file and parse (on 57b648b)

**Actual behaviour:**
no payment entries get created

**Expected behaviour:**
payment entries created

**Comment by lasalesi** [comment]
received_amount was assigned as unicode instead of float.

Resolved in df95ea1
